-- Customer Data Analytics
-- Database: customer_data_analytics

-- 1. Shopping distribution according to gender
SELECT 
    gender,
    COUNT(invoice_no) AS total_transactions
FROM customer_data
GROUP BY gender;

-- 2. Products sold by gender
SELECT 
    gender,
    SUM(quantity) AS total_products_sold
FROM customer_data
GROUP BY gender;

-- 3. Revenue generated by gender
SELECT 
    gender,
    SUM(quantity * price) AS total_revenue
FROM customer_data
GROUP BY gender;

-- 4. Shopping distribution by age group
SELECT 
    CASE
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 45 THEN '36-45'
        WHEN age BETWEEN 46 AND 60 THEN '46-60'
        ELSE '60+'
    END AS age_group,
    COUNT(invoice_no) AS total_transactions
FROM customer_data
GROUP BY age_group;

-- 5. Revenue by payment method
SELECT 
    payment_method,
    SUM(quantity * price) AS total_revenue
FROM customer_data
GROUP BY payment_method;

-- 6. Quantity sold by category
SELECT 
    category,
    SUM(quantity) AS total_quantity_sold
FROM customer_data
GROUP BY category;

